./rtl/amba_axi_pkg.sv
./rtl/dma_pkg.svh
./rtl/axi_to_cfgreg.sv
./rtl/dma_axi_if.sv
./rtl/dma_axi_wrapper.sv
./rtl/dma_csr.sv
./rtl/dma_fifo.sv
./rtl/dma_fsm.sv
./rtl/dma_func_wrapper.sv
./rtl/dma_streamer.sv
./rtl/tb/axi_mem_model.sv
./rtl/tb/tb_dma_axi_wrapper.sv